### PR TITLE
Fixed tigtone velocity inheritance and make tumult slightly more visible

### PR DESCRIPTION
**Pull request by Th3-spook**
Added a glowing particle to the tumult to make it a bit more visible from all angles (it was fine before but people complained so whatever), switched tigtone to inherit velocity with a desired speed of 0 on the frag. With inherit velocity turned off the pellets were affected by horizontal velocity more than other weapons would making it janky to aim as the lead indicator was inaccurate.

### CODE REVIEW

**Comment by BadM0dder** [comment]
Always use inherent velocity, unless you have a missile or shotgun

**Comment by BadM0dder** [comment]
If you have made sure the frags still spread then your good

**Comment by CommodoreChet** [comment]
Don't use the Scale attribute in the Ammo particle def. Scale the Particle directly.
It can be very inconsistent.

**Comment by Th3-spook** [comment]
it was something to do with the frags being interrupted mid flight and winding up slightly slower than the lead indicator showed so the trajectory itself would diverge from what it should be. It was the reason the pellets seemed to lag behind racs even though they have the same velocity

**Comment by Th3-spook** [comment]
> Don't use the Scale attribute in the Ammo particle def. Scale the Particle directly. It can be very inconsistent.

alright i'll adjust this

**Comment by BadM0dder** [comment]
> Don't use the Scale attribute in the Ammo particle def. Scale the Particle directly. It can be very inconsistent.

It's not that bad anymore, it's mainly for explosions (unattached particles), attached particles such as missile smoke have always been fine.

-source: dude trust me bro

**Comment by CommodoreChet** [comment]
something something best practice

**Review by InvalidArgument3 — APPROVED** [review]

**Pull request merged**
