### PR TITLE
t4 fix

### PR DESCRIPTION
**Pull request by BadM0dder**
remove decals

### CODE REVIEW

**Comment by BadM0dder** [comment]
[Update NHI_Cubeblocks.sbc](https://github.com/StarCoreSE/SCModRepository/pull/1480/commits/46f2eef6800de3ae40afa662a923fdcc3f0bed4e)

**Comment by InvalidArgument3** [comment]
>t4 fix
>look inside
>NHI_cubeblocks.sbc
image

**Comment by CommodoreChet** [comment]
no

**Comment by CommodoreChet** [comment]
I already have pending Description changes, Revert that push and ask next time.

**Review by CommodoreChet — CHANGES_REQUESTED** [review]
Noted Above

**Comment by BadM0dder** [comment]
> I already have pending Description changes, Revert that commit and ask first next time.

its been 1.5 years

**Comment by BadM0dder** [comment]
> > t4 fix
> > look inside
> > NHI_cubeblocks.sbc
> > image

u waited too long to merge

**Comment by BadM0dder** [comment]
now i dont feel like fixing it so ill just delete it i got more fun things to push :)

**Pull request closed without merging**
