### PR TITLE
Tibbs Throwing Wrenches At Serpent Arms

### PR DESCRIPTION
**Pull request by Tiberias42**
Tibbs has ideas, he would like to throw them at your face
----------------------------------------------------------------
=Charon Bonks=
>Idle Power: 100 -> 150
>Reload Power: ~464 -> ~600
>MaxTrack: 144 -> 120
>Reload: 6s -> 7s
>HeatPerShot: 1 -> 2
>Recoil:  More on real, Less on fake
>Fake Bullets: 4 -> 3
>Added 2km falloff (50%)
>RealShieldMod: 5x -> 4x
>FakeShieldMod removed

=Throwing Wrenches at Silvius=
-Intent: Standardized values between weapons
>Silvius BP: 370 -> 300
>AimTolerance: .01 -> 1
>ElevationRate: .05 -> .03
>IdlePower: 50 MW
>Reload: 10s -> 9s
>Cooldown: 0.95
>ReloadPower: ~200 MW
>Remove falloff
>Adjust modifiers: Armor, Comps & Shields all to 2x
>ShieldBypass: -1 -> -2
>BulletSpeed: 7000 m/s
>FragmentDamage: 50000 -> 47500

=Throwing Wrenches at Cerberus=
-Intent: Standardized values between weapons
>Cerberus: Still 900 BP
>DeviateShotAngles: .1 -> 0
>IdlePower: 50 MW per barrel
>ReloadPower: ~200 MW per barrel
>Reload: 10s -> 9s
>Cooldown: .05 -> .95
>Stagger fire between the 3 barrels

### CODE REVIEW

**Comment by Jnick-24** [comment]
Looks Good To Me:tm:

**Review by Jnick-24 — APPROVED** [review]
Looks Good To Me:tm:

**Review by InvalidArgument3 — APPROVED** [review]
it's probably fine

**Comment by CommodoreChet** [comment]
Who signed off on this?

**Comment by Tiberias42** [comment]
> Who signed off on this?
_*Insert yo mama joke here*_
The approvals are right there Chet, I know you can see them.

**Comment by CommodoreChet** [comment]
Go to Bed

**Pull request merged**
