### PR TITLE
Shhh

### PR DESCRIPTION
**Pull request by BadM0dder**
Supar Sekret Push.
Push Contains nothing.
Nothing is being pushed.
This is an extremely helpful description.

### CODE REVIEW

**Comment by Tiberias42** [comment]
https://youtu.be/TyEBeHvNJvE?si=tWAPtqSHQS8SyYdC

**Comment by BadM0dder** [comment]
https://youtu.be/SrDzsmzuJQs

**Comment by Tiberias42** [comment]
Where are the patch notes?!

**Comment by BadM0dder** [comment]
https://discord.com/channels/855480694137946153/1193783593907007628/1224963858364370984
https://discord.com/channels/855480694137946153/1193783593907007628/1225313192725446789

**Comment by InvalidArgument3** [comment]
>glance at PR, ok some LBX particles cool
>now contains longsword ammo, TIO guns getting +2km
this is extremely fucking annoying

**Comment by BadM0dder** [comment]
> > TIO guns getting +2km

wait what

**Comment by InvalidArgument3** [comment]
> > > TIO guns getting +2km
> 
> wait what

nvm now realize that was just a description update

**Pull request merged**
